// Generated by scripts/bundle-migrations.mjs. Do not edit; run `npm run db:generate`.
export type Migration = { name: string; statements: string[] };
export const MIGRATIONS: Migration[] = [
  {
    "name": "0000_init",
    "statements": [
      "CREATE TABLE `cooks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`tagline` text DEFAULT '' NOT NULL,\n\t`bio` text DEFAULT '' NOT NULL,\n\t`kitchen_story` text DEFAULT '' NOT NULL,\n\t`neighborhood` text NOT NULL,\n\t`zip` text NOT NULL,\n\t`specialties` text DEFAULT '[]' NOT NULL,\n\t`fulfillment` text DEFAULT '[\"pickup\"]' NOT NULL,\n\t`delivery_radius_miles` real DEFAULT 3 NOT NULL,\n\t`food_handler_certified` integer DEFAULT false NOT NULL,\n\t`kitchen_inspected` integer DEFAULT false NOT NULL,\n\t`years_cooking` integer DEFAULT 1 NOT NULL,\n\t`image_key` text DEFAULT 'cook-default' NOT NULL,\n\t`rating_avg` real DEFAULT 0 NOT NULL,\n\t`rating_count` integer DEFAULT 0 NOT NULL,\n\t`meals_served` integer DEFAULT 0 NOT NULL,\n\t`active` integer DEFAULT true NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `cooks_slug_unique` ON `cooks` (`slug`);",
      "CREATE INDEX `cooks_zip_idx` ON `cooks` (`zip`);",
      "CREATE INDEX `cooks_user_idx` ON `cooks` (`user_id`);",
      "CREATE TABLE `favorites` (\n\t`user_id` text NOT NULL,\n\t`meal_id` text NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`meal_id`) REFERENCES `meals`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `favorites_user_idx` ON `favorites` (`user_id`);",
      "CREATE TABLE `meals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`cook_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`slug` text NOT NULL,\n\t`description` text NOT NULL,\n\t`story` text DEFAULT '' NOT NULL,\n\t`cuisine` text NOT NULL,\n\t`price_cents` integer NOT NULL,\n\t`servings` integer DEFAULT 1 NOT NULL,\n\t`dietary_tags` text DEFAULT '[]' NOT NULL,\n\t`ingredients` text DEFAULT '[]' NOT NULL,\n\t`allergens` text DEFAULT '[]' NOT NULL,\n\t`image_key` text DEFAULT 'meal-default' NOT NULL,\n\t`available_days` text DEFAULT '[]' NOT NULL,\n\t`ready_window` text DEFAULT '5:00 - 7:00 pm' NOT NULL,\n\t`portions_available` integer DEFAULT 10 NOT NULL,\n\t`fulfillment` text DEFAULT '[\"pickup\"]' NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`rating_avg` real DEFAULT 0 NOT NULL,\n\t`rating_count` integer DEFAULT 0 NOT NULL,\n\t`times_ordered` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`cook_id`) REFERENCES `cooks`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `meals_slug_unique` ON `meals` (`slug`);",
      "CREATE INDEX `meals_cook_idx` ON `meals` (`cook_id`);",
      "CREATE INDEX `meals_status_idx` ON `meals` (`status`);",
      "CREATE TABLE `order_items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`meal_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`qty` integer NOT NULL,\n\t`unit_cents` integer NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`meal_id`) REFERENCES `meals`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `order_items_order_idx` ON `order_items` (`order_id`);",
      "CREATE TABLE `orders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`cook_id` text NOT NULL,\n\t`status` text DEFAULT 'placed' NOT NULL,\n\t`fulfillment` text NOT NULL,\n\t`address` text DEFAULT '' NOT NULL,\n\t`scheduled_for` text NOT NULL,\n\t`note` text DEFAULT '' NOT NULL,\n\t`subtotal_cents` integer NOT NULL,\n\t`fee_cents` integer DEFAULT 0 NOT NULL,\n\t`delivery_cents` integer DEFAULT 0 NOT NULL,\n\t`tip_cents` integer DEFAULT 0 NOT NULL,\n\t`total_cents` integer NOT NULL,\n\t`payment_ref` text DEFAULT '' NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\t`updated_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`cook_id`) REFERENCES `cooks`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `orders_user_idx` ON `orders` (`user_id`);",
      "CREATE INDEX `orders_cook_idx` ON `orders` (`cook_id`);",
      "CREATE TABLE `posts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`neighborhood` text NOT NULL,\n\t`kind` text DEFAULT 'post' NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text NOT NULL,\n\t`event_at` text,\n\t`likes` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `posts_neighborhood_idx` ON `posts` (`neighborhood`);",
      "CREATE TABLE `replies` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`post_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`body` text NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `replies_post_idx` ON `replies` (`post_id`);",
      "CREATE TABLE `reviews` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`cook_id` text NOT NULL,\n\t`meal_id` text,\n\t`order_id` text,\n\t`rating` integer NOT NULL,\n\t`comment` text DEFAULT '' NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`cook_id`) REFERENCES `cooks`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`meal_id`) REFERENCES `meals`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `reviews_meal_idx` ON `reviews` (`meal_id`);",
      "CREATE INDEX `reviews_cook_idx` ON `reviews` (`cook_id`);",
      "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`role` text DEFAULT 'customer' NOT NULL,\n\t`neighborhood` text DEFAULT '' NOT NULL,\n\t`zip` text DEFAULT '' NOT NULL,\n\t`address` text DEFAULT '' NOT NULL,\n\t`phone` text DEFAULT '' NOT NULL,\n\t`avatar_hue` integer DEFAULT 20 NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL\n);",
      "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);"
    ]
  },
  {
    "name": "0001_issues",
    "statements": [
      "CREATE TABLE `issues` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`cook_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`details` text DEFAULT '' NOT NULL,\n\t`status` text DEFAULT 'open' NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`cook_id`) REFERENCES `cooks`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `issues_order_idx` ON `issues` (`order_id`);"
    ]
  },
  {
    "name": "0002_waitlist",
    "statements": [
      "CREATE TABLE `waitlist` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`email` text NOT NULL,\n\t`zip` text DEFAULT '' NOT NULL,\n\t`neighborhood` text DEFAULT '' NOT NULL,\n\t`wants_to_cook` integer DEFAULT false NOT NULL,\n\t`note` text DEFAULT '' NOT NULL,\n\t`created_at` text DEFAULT (datetime('now')) NOT NULL\n);"
    ]
  }
];
